basePath: /_caltoph/v1
definitions:
  api.errormsg:
    properties:
      message:
        type: string
    type: object
  api.loginBody:
    properties:
      code:
        type: string
      provider:
        type: string
    required:
    - code
    - provider
    type: object
  api.loginReturn:
    properties:
      session_id:
        type: string
    type: object
  config.Oidc_provider:
    properties:
      client_id:
        type: string
      name:
        type: string
      url:
        type: string
      url_authorize:
        type: string
    type: object
info:
  contact: {}
  title: Caltoph API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: Authorize data from oidc provider
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/api.loginBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errormsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errormsg'
      summary: Perform a login action and create a session
  /auth/oidc_servers:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/config.Oidc_provider'
            type: array
      summary: Get oidc authentication providers
  /health:
    get:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get app health
swagger: "2.0"
